package:
  name: miplib
  version: "1.0"

source:
  git_rev: v1.0
  git_url: https://sakoho81@github.com/sakoho81/miplib.git

requirements:
  build:
    - python=3.6
    - setuptools
    - numpy

  run:
    - python=3.6
    - pims
    - pandas
    - h5py
    - matplotlib
    - numba=0.39
    - pyculib
    - SimpleITK
    - scipy
    - numpy
    - scikit-data
    - cudatoolkit=7.5
    - jpype1

  test:
    imports:
      - pyculib
      - miplib

  about:
    home: https://github.com/sakoho81/miplib
    license: BSD
    license_file: License.txt

